# Generated by Django 2.1.3 on 2018-11-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.TextField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField()),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranteeId', models.TextField()),
                ('Note', models.TextField()),
            ],
            options={
                'db_table': 'Guarantee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GuaranteeAndProduct',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GuaranteeAndProduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('installmentId', models.TextField(primary_key=True, serialize=False)),
                ('companyName', models.TextField()),
                ('credit', models.TextField()),
                ('note', models.TextField()),
                ('requiredInformation', models.TextField()),
            ],
            options={
                'db_table': 'Installment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstallmentAndProduct',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('installmentId', models.ForeignKey(db_column='installmentId', on_delete=django.db.models.deletion.CASCADE, to='site1.Installment')),
            ],
            options={
                'db_table': 'InstallmentAndProduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturerId', models.TextField(primary_key=True, serialize=False)),
                ('manufacturerName', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('City', models.TextField()),
                ('district', models.TextField()),
                ('street', models.TextField()),
            ],
            options={
                'db_table': 'Manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('phoneInfoId', models.TextField(primary_key=True, serialize=False)),
                ('phone3G', models.TextField()),
                ('phone4G', models.TextField()),
                ('dateStartSell', models.DateField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('thickness', models.FloatField(blank=True)),
                ('inch', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('resolution', models.TextField()),
                ('screenType', models.TextField()),
                ('simType', models.TextField()),
                ('simNumber', models.IntegerField(blank=True)),
                ('osType', models.TextField()),
                ('osVersion', models.TextField()),
                ('chipset', models.TextField()),
                ('GPU', models.TextField()),
                ('RAM', models.IntegerField(blank=True)),
                ('ROM', models.IntegerField(blank=True)),
                ('memoryCardSlot', models.TextField()),
                ('cameraBack', models.FloatField(blank=True)),
                ('cameraFront', models.FloatField(blank=True)),
                ('video', models.TextField()),
                ('WLAN', models.TextField()),
                ('bluetooth', models.TextField()),
                ('GPS', models.TextField()),
                ('NFC', models.TextField()),
                ('Pin', models.TextField()),
                ('price1', models.FloatField(blank=True)),
                ('price2', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'PhoneInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.TextField(primary_key=True, serialize=False)),
                ('postTitle', models.TextField()),
                ('postContent', models.TextField()),
                ('postLink', models.TextField()),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.TextField(primary_key=True, serialize=False)),
                ('productName', models.TextField()),
                ('productOtherNames', models.TextField(blank=True)),
                ('productCategoryId', models.ForeignKey(blank=True, db_column='productCategoryId', on_delete=django.db.models.deletion.CASCADE, to='site1.Category')),
                ('productManufacturerId', models.ForeignKey(blank=True, db_column='productManufacturerId', on_delete=django.db.models.deletion.CASCADE, to='site1.Manufacturer')),
                ('productPostId', models.ForeignKey(blank=True, db_column='productPostId', on_delete=django.db.models.deletion.CASCADE, to='site1.Post')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaleOff',
            fields=[
                ('saleOffId', models.TextField(primary_key=True, serialize=False)),
                ('saleOffPrice', models.FloatField(blank=True)),
                ('dateStart', models.DateField(blank=True)),
                ('dateEnd', models.DateField(blank=True)),
                ('other', models.TextField()),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='site1.Product')),
            ],
            options={
                'db_table': 'SaleOff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.TextField(primary_key=True, serialize=False)),
                ('storeName', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('City', models.TextField()),
                ('district', models.TextField()),
                ('street', models.TextField()),
            ],
            options={
                'db_table': 'Store',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('storeInventoryId', models.TextField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='site1.Product')),
                ('storeId', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.CASCADE, to='site1.Store')),
            ],
            options={
                'db_table': 'StoreInventory',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='phoneinfo',
            name='phoneProductId',
            field=models.ForeignKey(blank=True, db_column='phoneProductId', on_delete=django.db.models.deletion.CASCADE, to='site1.Product'),
        ),
        migrations.AddField(
            model_name='installmentandproduct',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='site1.Product'),
        ),
        migrations.AddField(
            model_name='guaranteeandproduct',
            name='installmentId',
            field=models.ForeignKey(db_column='installmentId', on_delete=django.db.models.deletion.CASCADE, to='site1.Installment'),
        ),
        migrations.AddField(
            model_name='guaranteeandproduct',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='site1.Product'),
        ),
    ]
