jango_isotope_gallery:
  project-latest_portfolio_block-7-15: '2'
  project-latest_portfolio_block-9-9: '1'
  project-latest_portfolio_block-8-25: '1'
  project-latest_portfolio_block-9-52: '1'
  project-latest_portfolio_block-7-47: '2'
  project-page_3-8-25: '2'
  project-page_3-9-9: '1'
  project-page_3-7-47: '1'
  project-page_3-10-18: '1'
  project-page_3-12-22: '1'
  project-page_3_2-15-18: '1'
  project-isotope_grid-11-18: '1'
  project-isotope_grid-10-18: '1'
  project-isotope_grid-8-25: '1'
  project-isotope_grid-9-9: '2'
  project-isotope_grid-7-47: '1'
  project-isotope_grid_overlay-18-16: '2'
  project-isotope_grid_overlay-14-12: '1'
  project-page_1-12-22: '2'
  project-page_1-13-18: '1'
  project-page_1-15-18: '1'
  project-page_1-11-18: '2'
  project-page_3_2-11-18: '2'
  project-page_3_2-9-9: '2'
  project-isotope_grid-9-151: '2'
  project-latest_portfolio_block-7-165: '2'
  project-isotope_grid_overlay-16-153: '2'
  project-page_3_2-10-161: '2'
  project-page_3_2-11-158: '2'
  project-page_3-8-163: '2'
  project-page_1-17-152: '2'
  project-page_1-13-156: '2'
