THEGIOIDIDONG_URLS = [
    "https://www.thegioididong.com/dtdd/samsung-galaxy-note-9",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-note8",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-note-9-512gb",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-s9-plus-128gb",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-s9-plus",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-s8-plus",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a8-plus-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a8-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a8-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a8-star",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a7-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a7-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-a6-2018",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-j8",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-j6-plus",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-j6-tim-lavender",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-j4",
    "https://www.thegioididong.com/dtdd/samsung-galaxy-j4-plus",

    "https://www.thegioididong.com/dtdd/iphone-xs-max-512gb",
    "https://www.thegioididong.com/dtdd/iphone-xs-512gb",
    "https://www.thegioididong.com/dtdd/iphone-xs-max-256gb",
    "https://www.thegioididong.com/dtdd/iphone-xs-256gb",
    "https://www.thegioididong.com/dtdd/iphone-xs-max",
    "https://www.thegioididong.com/dtdd/iphone-x-256gb",
    "https://www.thegioididong.com/dtdd/iphone-x-64gb",
    "https://www.thegioididong.com/dtdd/iphone-8-256gb",
    "https://www.thegioididong.com/dtdd/iphone-8-64gb",
    "https://www.thegioididong.com/dtdd/iphone-7-plus-128gb",
    "https://www.thegioididong.com/dtdd/iphone-7-256gb",
    "https://www.thegioididong.com/dtdd/iphone-7-plus",
    "https://www.thegioididong.com/dtdd/iphone-7",
    "https://www.thegioididong.com/dtdd/iphone-6s-32gb",
    "https://www.thegioididong.com/dtdd/iphone-6s-plus-32gb",
    "https://www.thegioididong.com/dtdd/iphone-6-32gb-gold",

    "https://www.thegioididong.com/dtdd/realme-2-pro",

    "https://www.thegioididong.com/dtdd/oppo-find-x",
    "https://www.thegioididong.com/dtdd/oppo-f9-6gb",
    "https://www.thegioididong.com/dtdd/oppo-f9",
    "https://www.thegioididong.com/dtdd/oppo-f9-tim",
    "https://www.thegioididong.com/dtdd/oppo-f7",
    "https://www.thegioididong.com/dtdd/oppo-f7-youth",
    "https://www.thegioididong.com/dtdd/oppo-f5-youth",
    "https://www.thegioididong.com/dtdd/oppo-a3s-32gb",
    "https://www.thegioididong.com/dtdd/oppo-a71-32gb-2018",

    "https://www.thegioididong.com/dtdd/nokia-7-plus",
    "https://www.thegioididong.com/dtdd/nokia-61-plus",
    "https://www.thegioididong.com/dtdd/nokia-6-new-64gb",
    "https://www.thegioididong.com/dtdd/nokia-6",
    "https://www.thegioididong.com/dtdd/nokia-6-2018",
    "https://www.thegioididong.com/dtdd/nokia-51-plus",
    "https://www.thegioididong.com/dtdd/nokia-31",

    "https://www.thegioididong.com/dtdd/vivo-v11"
]