PATH_FILE_TRAIN = 'xeras/nlp/train/train_data.csv'
PATH_FILE_SAME_WORDS = 'xeras/nlp/train/same_words.csv'
PATH_VALIDATE_DATA_TRAIN = 'xeras/nlp/train/validate_data_train.txt'
PATH_MODEL_NER = 'xeras/nlp/ner/model'
PATH_LOGS_NER = 'xeras/nlp/ner/logs/ner_logs.csv'
PATH_CORRECT_SENTENCES = 'xeras/nlp/test_results/correct_sentences.xlsx'
PATH_WRONG_SENTENCES = 'xeras/nlp/test_results/wrong_sentences.xlsx'
PATH_TEST_ACCURACY = 'xeras/nlp/test_results/test_accurary.txt'
PATH_ALL_TYPE_ASK = 'xeras/nlp/test_results/all_type_asks.txt'
PATH_ALL_ENTITIES = 'xeras/nlp/test_results/all_entities.json'
DEFAULT_LINES_LIMITATION = 1100
DEFAULT_NER_TIERS = 100
DEFAULT_IS_USED_MODEL = False
DEFAULT_IS_USED_SAME_WORDS = True
SAMPLE_SENTENCE = 'Ipx giá nhiêu nhỉ'
